/**
 * Contract Templates for Pipeline Gigs
 *
 * Templates for each phase of startup/vibecoin creation:
 * Discovery → Design → Development → Launch → Marketing → Operations → Scale
 */

import { ContractTemplate, PipelinePhase } from './types';

// Base contract header (shared across all templates)
const CONTRACT_HEADER = `
# {{contractTitle}}

**Contract ID:** {{contractId}}
**Date:** {{contractDate}}
**Jurisdiction:** {{jurisdiction}}

---

## PARTIES

**Client ("the Client"):**
- Name: {{clientName}}
- Email: {{clientEmail}}
{{#clientCompany}}- Company: {{clientCompany}} ({{clientCompanyNumber}}){{/clientCompany}}
{{#clientWallet}}- Wallet: {{clientWallet}}{{/clientWallet}}

**Contractor ("the Contractor"):**
- Name: {{contractorName}}
- Email: {{contractorEmail}}
{{#contractorLinkedIn}}- LinkedIn: {{contractorLinkedIn}}{{/contractorLinkedIn}}
{{#contractorWallet}}- Wallet: {{contractorWallet}}{{/contractorWallet}}

---
`;

// Base contract footer (shared across all templates)
const CONTRACT_FOOTER = `
---

## PAYMENT TERMS

**Total Contract Value:** {{paymentAmount}} {{paymentCurrency}}
**Payment Schedule:** {{paymentSchedule}}

{{#milestones}}
### Milestones
{{#each milestones}}
- **{{description}}**: {{amount}} {{../paymentCurrency}} (Due: {{dueDate}})
{{/each}}
{{/milestones}}

{{#escrowRequired}}
**Escrow:** Funds held in escrow via {{escrowPlatform}} until deliverables accepted.
{{/escrowRequired}}

---

## GENERAL TERMS

### Confidentiality
Both parties agree to keep confidential any proprietary information shared during this engagement.

### Intellectual Property
Upon full payment, all work product and intellectual property created under this contract transfers to the Client.

### Dispute Resolution
Any disputes shall first attempt resolution through good-faith negotiation. If unresolved within 14 days, disputes shall be resolved under the laws of {{jurisdiction}}.

### Termination
Either party may terminate with 7 days written notice. Contractor shall be paid for work completed to date.

### Amendments
This contract may only be amended in writing, signed by both parties, and inscribed on-chain.

---

## BLOCKCHAIN INSCRIPTION

This contract will be inscribed on the BSV blockchain as a 1Sat Ordinal upon signing, creating immutable proof of:
- Contract terms and conditions
- Both party signatures
- Timestamp of agreement

**Inscription Protocol:** b0ase Pipeline Contract v1.0

---

## SIGNATURES

By signing below, both parties agree to the terms of this contract.

**Client Signature:**
- Signed: {{clientSignature}}
- Date: {{clientSignedAt}}
- Method: {{clientSignMethod}}

**Contractor Signature:**
- Signed: {{contractorSignature}}
- Date: {{contractorSignedAt}}
- Method: {{contractorSignMethod}}

---

*Contract Hash: {{contentHash}}*
*Generated by b0ase Pipeline System*
`;

// ============================================================================
// DISCOVERY PHASE TEMPLATES
// ============================================================================

const MARKET_RESEARCH_TEMPLATE: ContractTemplate = {
  id: 'discovery-market-research',
  name: 'Market Research Contract',
  description: 'Contract for market research, competitor analysis, and opportunity identification.',
  phase: 'discovery',
  category: 'research',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide market research services for {{projectName}} including:

### Research Deliverables
1. **Market Analysis Report**
   - Market size and growth projections
   - Key trends and drivers
   - Target audience segmentation

2. **Competitor Analysis**
   - Identification of {{competitorCount}} key competitors
   - Feature comparison matrix
   - Pricing analysis
   - SWOT analysis

3. **Opportunity Assessment**
   - Gap analysis
   - Positioning recommendations
   - Go-to-market considerations

### Timeline
- **Start Date:** {{startDate}}
- **Research Phase:** {{researchDuration}} days
- **Final Delivery:** {{endDate}}

### Acceptance Criteria
- All research data sourced and cited
- Executive summary included
- Actionable recommendations provided
- Presentation deck for stakeholders

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Name of the project being researched' },
    { name: 'competitorCount', type: 'number', description: 'Number of competitors to analyze', default: '5' },
    { name: 'researchDuration', type: 'number', description: 'Days for research phase', default: '14' },
  ],
  defaultPayment: {
    totalAmount: 500,
    currency: 'GBP',
    paymentSchedule: 'milestone',
    escrowRequired: true,
  },
  defaultDeliverables: [
    { title: 'Market Analysis Report', description: 'Comprehensive market analysis document' },
    { title: 'Competitor Matrix', description: 'Detailed competitor comparison' },
    { title: 'Opportunity Assessment', description: 'Strategic recommendations' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['research', 'market-analysis', 'discovery', 'strategy'],
};

// ============================================================================
// DESIGN PHASE TEMPLATES
// ============================================================================

const UI_UX_DESIGN_TEMPLATE: ContractTemplate = {
  id: 'design-ui-ux',
  name: 'UI/UX Design Contract',
  description: 'Contract for user interface and experience design services.',
  phase: 'design',
  category: 'design',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide UI/UX design services for {{projectName}}:

### Design Deliverables
1. **User Research & Personas**
   - User interview synthesis ({{userInterviews}} interviews)
   - Persona documentation
   - User journey maps

2. **Information Architecture**
   - Site map / app structure
   - Navigation design
   - Content hierarchy

3. **UI Design**
   - Wireframes for {{screenCount}} screens
   - High-fidelity mockups
   - Design system / component library
   - Responsive variants (desktop, tablet, mobile)

4. **Prototyping**
   - Interactive prototype in Figma
   - User flow demonstrations
   - Handoff documentation for developers

### Design Tools
Primary design tool: {{designTool}}
Handoff format: {{handoffFormat}}

### Timeline
- **Discovery:** {{discoveryDays}} days
- **Wireframing:** {{wireframeDays}} days
- **Visual Design:** {{visualDays}} days
- **Revisions:** {{revisionRounds}} rounds included

### Acceptance Criteria
- All screens designed to specification
- Design system documented
- Developer handoff complete
- Source files provided

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Project name' },
    { name: 'screenCount', type: 'number', description: 'Number of screens to design', default: '10' },
    { name: 'userInterviews', type: 'number', description: 'Number of user interviews', default: '5' },
    { name: 'designTool', type: 'string', description: 'Primary design tool', default: 'Figma' },
    { name: 'handoffFormat', type: 'string', description: 'Developer handoff format', default: 'Figma Dev Mode' },
    { name: 'revisionRounds', type: 'number', description: 'Included revision rounds', default: '2' },
  ],
  defaultPayment: {
    totalAmount: 2000,
    currency: 'GBP',
    paymentSchedule: 'milestone',
    escrowRequired: true,
  },
  defaultDeliverables: [
    { title: 'User Research', description: 'Personas and journey maps' },
    { title: 'Wireframes', description: 'Low-fidelity wireframes' },
    { title: 'Visual Design', description: 'High-fidelity mockups' },
    { title: 'Design System', description: 'Component library and documentation' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['design', 'ui', 'ux', 'figma', 'wireframes'],
};

// ============================================================================
// DEVELOPMENT PHASE TEMPLATES
// ============================================================================

const FULLSTACK_DEV_TEMPLATE: ContractTemplate = {
  id: 'development-fullstack',
  name: 'Full Stack Development Contract',
  description: 'Contract for full stack web/app development services.',
  phase: 'development',
  category: 'technical',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide full stack development services for {{projectName}}:

### Technical Requirements
- **Frontend:** {{frontendStack}}
- **Backend:** {{backendStack}}
- **Database:** {{database}}
- **Hosting:** {{hosting}}

### Development Deliverables
1. **Core Application**
   - {{featureCount}} features as specified
   - Responsive design implementation
   - API development and documentation

2. **Infrastructure**
   - Development environment setup
   - CI/CD pipeline configuration
   - Production deployment

3. **Quality Assurance**
   - Unit tests (minimum {{testCoverage}}% coverage)
   - Integration tests
   - Performance optimization

4. **Documentation**
   - Technical documentation
   - API documentation
   - Deployment guide

### Code Standards
- All code in TypeScript (strict mode)
- ESLint + Prettier configuration
- Git workflow with PR reviews
- No secrets in codebase

### Repository
Code will be committed to: {{repoUrl}}

### Timeline
- **Sprint Duration:** {{sprintLength}} weeks
- **Total Sprints:** {{sprintCount}}
- **Estimated Completion:** {{endDate}}

### Acceptance Criteria
- All features functional per specification
- Tests passing
- Code review approved
- Documentation complete
- Deployed to production

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Project name' },
    { name: 'frontendStack', type: 'string', description: 'Frontend technology', default: 'Next.js + React + TypeScript' },
    { name: 'backendStack', type: 'string', description: 'Backend technology', default: 'Next.js API Routes + Prisma' },
    { name: 'database', type: 'string', description: 'Database', default: 'PostgreSQL (Supabase)' },
    { name: 'hosting', type: 'string', description: 'Hosting platform', default: 'Vercel' },
    { name: 'featureCount', type: 'number', description: 'Number of features', default: '10' },
    { name: 'testCoverage', type: 'number', description: 'Minimum test coverage %', default: '70' },
    { name: 'sprintLength', type: 'number', description: 'Sprint length in weeks', default: '2' },
    { name: 'sprintCount', type: 'number', description: 'Number of sprints', default: '4' },
    { name: 'repoUrl', type: 'string', description: 'GitHub repository URL' },
  ],
  defaultPayment: {
    totalAmount: 5000,
    currency: 'GBP',
    paymentSchedule: 'milestone',
    escrowRequired: true,
  },
  defaultDeliverables: [
    { title: 'Sprint 1', description: 'Core infrastructure and authentication' },
    { title: 'Sprint 2', description: 'Primary features' },
    { title: 'Sprint 3', description: 'Secondary features and integrations' },
    { title: 'Sprint 4', description: 'Testing, polish, and deployment' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['development', 'fullstack', 'nextjs', 'react', 'typescript'],
};

const SMART_CONTRACT_TEMPLATE: ContractTemplate = {
  id: 'development-smart-contract',
  name: 'Smart Contract Development',
  description: 'Contract for blockchain smart contract development and audit.',
  phase: 'development',
  category: 'technical',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to develop smart contracts for {{projectName}}:

### Blockchain Platform
- **Network:** {{blockchain}}
- **Token Standard:** {{tokenStandard}}
- **Testnet:** {{testnet}}

### Smart Contract Deliverables
1. **Token Contract**
   - Token name: {{tokenName}}
   - Symbol: {{tokenSymbol}}
   - Total supply: {{totalSupply}}
   - Features: {{tokenFeatures}}

2. **Supporting Contracts**
{{#additionalContracts}}
   - {{name}}: {{description}}
{{/additionalContracts}}

3. **Security**
   - Internal security review
   - Test coverage minimum {{testCoverage}}%
   - Gas optimization

4. **Documentation**
   - Contract documentation
   - Deployment guide
   - Interaction examples

### Audit Requirements
{{#auditRequired}}
Third-party audit by {{auditFirm}} included in scope.
{{/auditRequired}}
{{^auditRequired}}
Third-party audit NOT included. Client may arrange separately.
{{/auditRequired}}

### Deployment
- Testnet deployment included
- Mainnet deployment: {{mainnetDeployment}}

### Acceptance Criteria
- All contracts compile without errors
- Tests passing on testnet
- Security checklist completed
- Documentation complete

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Project name' },
    { name: 'blockchain', type: 'string', description: 'Target blockchain', default: 'BSV' },
    { name: 'tokenStandard', type: 'string', description: 'Token standard', default: 'BSV-20' },
    { name: 'testnet', type: 'string', description: 'Testnet network' },
    { name: 'tokenName', type: 'string', description: 'Token name' },
    { name: 'tokenSymbol', type: 'string', description: 'Token symbol' },
    { name: 'totalSupply', type: 'string', description: 'Total token supply' },
    { name: 'tokenFeatures', type: 'string', description: 'Token features', default: 'Mintable, Transferable' },
    { name: 'testCoverage', type: 'number', description: 'Test coverage %', default: '90' },
    { name: 'mainnetDeployment', type: 'string', description: 'Mainnet deployment terms', default: 'Included' },
  ],
  defaultPayment: {
    totalAmount: 3000,
    currency: 'GBP',
    paymentSchedule: 'milestone',
    escrowRequired: true,
  },
  defaultDeliverables: [
    { title: 'Contract Development', description: 'Smart contract code' },
    { title: 'Testing', description: 'Test suite and coverage' },
    { title: 'Documentation', description: 'Technical documentation' },
    { title: 'Deployment', description: 'Testnet and mainnet deployment' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['blockchain', 'smart-contract', 'token', 'bsv', 'crypto'],
};

// ============================================================================
// MARKETING PHASE TEMPLATES
// ============================================================================

const SOCIAL_MEDIA_TEMPLATE: ContractTemplate = {
  id: 'marketing-social-media',
  name: 'Social Media Management Contract',
  description: 'Contract for social media content creation and community management.',
  phase: 'marketing',
  category: 'social-media',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide social media management for {{projectName}}:

### Platforms
{{#platforms}}
- {{name}}: {{handle}}
{{/platforms}}

### Content Deliverables
1. **Content Creation**
   - {{postsPerWeek}} posts per week per platform
   - Content calendar (monthly)
   - Graphics and visuals
   - Hashtag strategy

2. **Community Management**
   - Daily monitoring and engagement
   - Response to comments/DMs within {{responseTime}} hours
   - Community growth tactics
   - Influencer outreach

3. **Reporting**
   - Weekly performance metrics
   - Monthly analytics report
   - Growth recommendations

### Content Guidelines
- Brand voice: {{brandVoice}}
- Visual style: {{visualStyle}}
- Prohibited topics: {{prohibited}}

### Performance Targets
- Follower growth: {{growthTarget}}% per month
- Engagement rate: {{engagementTarget}}%

### Timeline
- **Contract Duration:** {{contractDuration}} months
- **Start Date:** {{startDate}}

### Acceptance Criteria
- Content calendar delivered on time
- Posts published as scheduled
- Engagement metrics tracked
- Monthly reports delivered

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Project/brand name' },
    { name: 'postsPerWeek', type: 'number', description: 'Posts per week per platform', default: '5' },
    { name: 'responseTime', type: 'number', description: 'Max response time in hours', default: '4' },
    { name: 'brandVoice', type: 'string', description: 'Brand voice description', default: 'Professional but approachable' },
    { name: 'visualStyle', type: 'string', description: 'Visual style guide', default: 'Per brand guidelines' },
    { name: 'prohibited', type: 'string', description: 'Prohibited content', default: 'Political, controversial topics' },
    { name: 'growthTarget', type: 'number', description: 'Monthly growth target %', default: '10' },
    { name: 'engagementTarget', type: 'number', description: 'Engagement rate target %', default: '3' },
    { name: 'contractDuration', type: 'number', description: 'Contract duration in months', default: '3' },
  ],
  defaultPayment: {
    totalAmount: 500,
    currency: 'GBP',
    paymentSchedule: 'recurring',
    escrowRequired: false,
  },
  defaultDeliverables: [
    { title: 'Content Calendar', description: 'Monthly content plan' },
    { title: 'Content Creation', description: 'Posts, graphics, copy' },
    { title: 'Community Management', description: 'Daily engagement' },
    { title: 'Monthly Report', description: 'Analytics and recommendations' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['marketing', 'social-media', 'content', 'community'],
};

// ============================================================================
// OPERATIONS PHASE TEMPLATES
// ============================================================================

const COMMUNITY_MOD_TEMPLATE: ContractTemplate = {
  id: 'operations-community-mod',
  name: 'Community Moderation Contract',
  description: 'Contract for Discord/Telegram community moderation services.',
  phase: 'operations',
  category: 'community',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide community moderation for {{projectName}}:

### Platforms
{{#communities}}
- {{platform}}: {{link}}
{{/communities}}

### Moderation Duties
1. **Active Moderation**
   - Monitor channels during {{coverageHours}}
   - Enforce community guidelines
   - Remove spam, scams, inappropriate content
   - Warn/timeout/ban rule violators

2. **Community Support**
   - Answer member questions
   - Escalate technical issues to team
   - Welcome new members
   - Facilitate discussions

3. **Reporting**
   - Daily activity log
   - Weekly incident report
   - Member feedback summary

### Coverage Schedule
- **Hours:** {{coverageHours}}
- **Timezone:** {{timezone}}
- **Response Time:** Within {{responseMinutes}} minutes during coverage

### Tools Access Required
- Discord/Telegram admin access
- Moderation bot access
- Knowledge base access

### Escalation Path
- Level 1: Contractor handles
- Level 2: Escalate to {{escalationContact}}
- Emergency: {{emergencyContact}}

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Community/project name' },
    { name: 'coverageHours', type: 'string', description: 'Coverage hours', default: '9am-6pm GMT' },
    { name: 'timezone', type: 'string', description: 'Timezone', default: 'GMT' },
    { name: 'responseMinutes', type: 'number', description: 'Response time in minutes', default: '15' },
    { name: 'escalationContact', type: 'string', description: 'Escalation contact' },
    { name: 'emergencyContact', type: 'string', description: 'Emergency contact' },
  ],
  defaultPayment: {
    totalAmount: 300,
    currency: 'GBP',
    paymentSchedule: 'recurring',
    escrowRequired: false,
  },
  defaultDeliverables: [
    { title: 'Daily Moderation', description: 'Active community moderation' },
    { title: 'Support', description: 'Member support and engagement' },
    { title: 'Reporting', description: 'Activity and incident reports' },
  ],
  jurisdiction: 'England & Wales',
  tags: ['community', 'moderation', 'discord', 'telegram', 'support'],
};

// ============================================================================
// GENERIC/FLEXIBLE TEMPLATE
// ============================================================================

const FLEXIBLE_GIG_TEMPLATE: ContractTemplate = {
  id: 'flexible-gig',
  name: 'Flexible Gig Contract',
  description: 'Flexible contract template for custom gig arrangements.',
  phase: 'operations',
  category: 'general',
  version: '1.0.0',
  content: `${CONTRACT_HEADER}

## SCOPE OF WORK

The Contractor agrees to provide services for {{projectName}} as follows:

### Description
{{scopeDescription}}

### Deliverables
{{#deliverables}}
{{index}}. **{{title}}**
   {{description}}
   {{#acceptanceCriteria}}
   - {{.}}
   {{/acceptanceCriteria}}
{{/deliverables}}

### Timeline
- **Start Date:** {{startDate}}
- **End Date:** {{endDate}}
- **Estimated Hours:** {{estimatedHours}}

### Working Arrangements
- **Communication:** {{communicationChannel}}
- **Check-ins:** {{checkInFrequency}}
- **Timezone:** {{timezone}}

### Additional Terms
{{additionalTerms}}

${CONTRACT_FOOTER}`,

  requiredVariables: [
    { name: 'projectName', type: 'string', description: 'Project name' },
    { name: 'scopeDescription', type: 'string', description: 'Detailed scope description' },
    { name: 'estimatedHours', type: 'number', description: 'Estimated hours' },
    { name: 'communicationChannel', type: 'string', description: 'Primary communication', default: 'Discord' },
    { name: 'checkInFrequency', type: 'string', description: 'Check-in frequency', default: 'Weekly' },
    { name: 'timezone', type: 'string', description: 'Working timezone', default: 'GMT' },
    { name: 'additionalTerms', type: 'string', description: 'Any additional terms', default: 'None' },
  ],
  defaultPayment: {
    totalAmount: 0,
    currency: 'GBP',
    paymentSchedule: 'milestone',
    escrowRequired: true,
  },
  defaultDeliverables: [],
  jurisdiction: 'England & Wales',
  tags: ['flexible', 'custom', 'gig'],
};

// ============================================================================
// TEMPLATE REGISTRY
// ============================================================================

export const CONTRACT_TEMPLATES: Record<string, ContractTemplate> = {
  // Discovery
  'discovery-market-research': MARKET_RESEARCH_TEMPLATE,

  // Design
  'design-ui-ux': UI_UX_DESIGN_TEMPLATE,

  // Development
  'development-fullstack': FULLSTACK_DEV_TEMPLATE,
  'development-smart-contract': SMART_CONTRACT_TEMPLATE,

  // Marketing
  'marketing-social-media': SOCIAL_MEDIA_TEMPLATE,

  // Operations
  'operations-community-mod': COMMUNITY_MOD_TEMPLATE,

  // Flexible
  'flexible-gig': FLEXIBLE_GIG_TEMPLATE,
};

// Get templates by phase
export function getTemplatesByPhase(phase: PipelinePhase): ContractTemplate[] {
  return Object.values(CONTRACT_TEMPLATES).filter(t => t.phase === phase);
}

// Get template by ID
export function getTemplateById(id: string): ContractTemplate | undefined {
  return CONTRACT_TEMPLATES[id];
}

// Get all templates
export function getAllTemplates(): ContractTemplate[] {
  return Object.values(CONTRACT_TEMPLATES);
}

// Map gig category to template
export function getTemplateForGigCategory(category: string): ContractTemplate {
  const mapping: Record<string, string> = {
    'Social Media': 'marketing-social-media',
    'Technical': 'development-fullstack',
    'Marketing': 'marketing-social-media',
    'Creative': 'design-ui-ux',
    'Community': 'operations-community-mod',
    'Research': 'discovery-market-research',
  };

  const templateId = mapping[category] || 'flexible-gig';
  return CONTRACT_TEMPLATES[templateId];
}
