export interface BlogPost {
    slug: string;
    title: string;
    description: string;
    author: {
        name: string;
        handle?: string;
        url?: string;
    };
    company?: {
        name: string;
        url?: string;
        stats?: string;
    };
    date: string;
    readTime: string;
    tags: string[];
    featured?: boolean;
    image?: string;
    video?: string;
}

export const blogPosts: BlogPost[] = [
    {
        slug: 'bitcoin-corporation-model',
        title: "Fork the Code, Fork the Token: The Bitcoin Corporation Model",
        description: "What happens when open-source contributors can fork the equity, not just the repository? A new business model where code forks become stock splits.",
        date: '2026-02-08',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '10 min read',
        tags: ['bitcoin-corporation', 'open-source', 'forking', 'equity', 'tokens', '$401', '$402', 'kintsugi'],
        featured: true,
        image: '/blog/bitcoin-corporation-model.jpg'
    },
    {
        slug: 'bitcoin-corporation-business-model',
        title: "The Bitcoin Corporation — Business Model",
        description: "How The Bitcoin Corporation generates revenue through on-chain inscription services and tokenised domain infrastructure.",
        date: '2026-02-08',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['bitcoin-corporation', 'business-model', 'inscriptions', 'tokens', '$402', 'dns-dex'],
        featured: true,
        image: '/blog/penny-corporation.jpg'
    },
    {
        slug: 'tiny-capital-partners',
        title: "Tiny Capital Partners",
        description: "A zero-capital venture partnership model where The Bitcoin Corporation provides infrastructure in exchange for a minority equity position.",
        date: '2026-02-08',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['tiny-capital', 'venture', 'partnership', 'dns-dex', 'tokens', '$402', 'equity'],
        featured: true,
        image: '/blog/TINY.jpg'
    },
    {
        slug: '402-protocol-blog-series',
        title: "The $402 Protocol: A Seven-Part Exploration of the Tokenised Internet",
        description: "From micro-speculation to the stock exchange where every ticker is a URL. A complete series on the tokenised internet.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['$402', 'protocol', 'bitcoin', 'tokens', 'identity', 'series', 'dns-dex'],
        featured: true,
        image: '/blog/402-series.jpg'
    },
    {
        slug: 'dns-dex-stock-exchange-urls',
        title: "DNS-DEX: The Stock Exchange Where Every Ticker Is a URL",
        description: "How a TXT record, a token, and a 51% vote turn any domain name into a publicly traded company.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['dns-dex', '$402', '$401', '$403', 'domains', 'tokens', 'exchange', 'governance'],
        featured: true,
        image: '/blog/dns-dex-2.jpg'
    },
    {
        slug: '401-cinema-ticket-id-check',
        title: "$401: The Cinema Ticket and the ID Check",
        description: "A standard for proving who you are, what you own, and what you're willing to stake your name on.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['$401', '$402', 'identity', 'tokens', 'protocol', 'peer-review'],
        featured: true,
        image: '/blog/401-cinema-ticket.jpg'
    },
    {
        slug: '401-402-red-blue-blood',
        title: "$401 and $402: Red Blood and Blue Blood",
        description: "Why identity tokens flow one way, content tokens flow the other, and neither one is money.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '14 min read',
        tags: ['$401', '$402', 'identity', 'tokens', 'securities', 'pseudonymity', 'protocol'],
        featured: true,
        image: '/blog/red-blue-blood.jpg'
    },
    {
        slug: '401-identity-token-peers-underwrite',
        title: "$401: The Identity Token That Your Peers Underwrite",
        description: "Not a social credit score. Not a KYC checkbox. A financial instrument that prices how much the world trusts you.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '15 min read',
        tags: ['identity', 'bitcoin', 'tokens', 'protocol', 'reputation', '$401'],
        featured: true,
        image: '/blog/401-identity-token.png'
    },
    {
        slug: '402-ecosystem-identity-code-tokens',
        title: "The $402 Ecosystem: A Modular Internet Where Everything Has a Price and Everyone Has a Name",
        description: "Identity tokens, content tokens, code tokens, and the client that binds them all.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '13 min read',
        tags: ['$402', 'ecosystem', 'identity', 'bitcoin-writer', 'bitcoin-code', 'protocol'],
        featured: true,
        image: '/blog/402-ecosystem.jpg'
    },
    {
        slug: 'micro-capital-micro-speculation-economy',
        title: "Micro Capital: The Micro-Speculation Economy",
        description: "How penny bets, tokenised browsing, and data DNA turn every internet user into a hedge fund.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '13 min read',
        tags: ['micro-capital', 'finance', 'tokens', 'scrollpay', 'data-dna', 'speculation'],
        featured: true,
        image: '/blog/micro-speculation-economy.png'
    },
    {
        slug: 'micro-capital-worlds-smallest-hedge-fund',
        title: "Micro Capital: The World's Smallest Hedge Fund",
        description: "How one founder is proving that hedge funds don't need billions to be brilliant. AI-native architecture, asymmetric betting, and the case against AUM.",
        date: '2026-02-09',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['micro-capital', 'finance', 'ai', 'hedge-fund', 'automation', 'tokens'],
        featured: true,
        image: '/blog/micro-capital-hedge-fund.png'
    },
    {
        slug: 'the-adventures-of-kweg-wong-esq',
        title: "The Adventures of Kweg Wong esq.: The Man Who Became a Narrative Machine",
        description: "Who is Sir Dr. Professorr Kweg Wong esq.? A study in the Infinite Narrative Loop and the $402 Content Flywheel.",
        date: '2026-02-06',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ['kweg-wong', 'narrative-machine', 'f.news', 'satire', 'ai-agents', '$402'],
        featured: true,
        image: '/images/blog/kweg-adventures.png'
    },
    {
        slug: 'the-payout-engine',
        title: "Path402d Is Downloadable: Mine $402, Bootstrap the Network",
        description: "The $402 desktop app is live. Download it, configure your wallet, and start mining. We need peers to bootstrap the gossip network.",
        date: '2026-02-07',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['$402', 'mining', 'desktop', 'gossip', 'htm', 'download'],
        featured: true,
        image: '/images/blog/payout-engine.jpg'
    },
    {
        slug: 'ai-is-a-conduit-for-intelligence',
        title: "AI Is a Conduit for Intelligence, Not a Replacement for It",
        description: "AI isn't thinking for you. It's channelling the accumulated weight of human thought through you, with less friction than has ever been possible before.",
        date: '2026-02-07',
        author: { name: 'Richard Boase', url: 'https://b0ase.com', handle: 'b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ['ai', 'philosophy', 'intelligence', 'buddhism', 'knowledge'],
        featured: true,
        image: '/blog/ai-conduit-intelligence.png'
    },
    {
        slug: 'the-402-standard',
        title: "The $402 Standard",
        description: "The canonical specification for $402 tokens: payment handles, revenue splits, staking, and access rights. This is how it works.",
        date: '2026-02-04',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['$402', 'standard', 'protocol', 'specification', 'tokens'],
        featured: true,
        image: '/images/blog/the-402-standard.jpg'
    },
    {
        slug: 'the-last-play',
        title: "The Last Play",
        description: "A satire about artificial scarcity, and then a real alternative. What if the incentives ran the other way?",
        date: '2026-02-04',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '10 min read',
        tags: ['$402', 'tokens', 'scarcity', 'music', 'culture', 'economics'],
        featured: true,
        image: '/images/blog/the-last-play.jpg'
    },
    {
        slug: 'dns-dex-domain-tokenization',
        title: "DNS-DEX: The Exchange for Tokenized Domains",
        description: "DNS-DEX is where domain tokens trade. Owners set their own pricing, revenue distribution, and access rules. The protocol enables. You decide.",
        date: '2026-02-03',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['dns-dex', '$402', 'domain tokenization', 'web monetization', 'bsv'],
        featured: true,
        image: '/blog/dns-dex-hero.jpg'
    },
    {
        slug: 'pathd-is-live',
        title: "Introducing $pathd: The Path 402 Network Daemon",
        description: "What if running a node meant choosing what content to serve? $pathd brings BitTorrent-style curation to tokenized content with PoW accountability.",
        date: '2026-02-03',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['$402', 'pathd', 'MCP', 'BSV', 'AI Agents', 'Daemon'],
        featured: true,
        image: '/images/blog/pathd-daemon.jpg'
    },
    {
        slug: 'every-url-is-a-path',
        title: "Every URL Is a $PATH",
        description: "Your website has paths. Mine have prices. Put a $ in front of a URL path and it becomes a market with economics, participants, and revenue.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['$402', 'Micropayments', 'MetaWeb', 'AI Agents', 'Content Monetization'],
        featured: true,
        image: '/dollar_path_code_visualization_1769978701391.jpg'
    },
    {
        slug: 'metaweb-mathematics',
        title: "The Maths of the MetaWeb: Pricing, Revenue, and the Economics of Tokenised Content",
        description: "The mathematical foundations of MetaWeb pricing models and revenue distribution. Square root decay, issuer shares, and why the numbers favour early participants.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '15 min read',
        tags: ['MetaWeb', 'Economics', 'Pricing', 'Mathematics', 'Tokens'],
        featured: true,
        image: '/metaweb_economic_curve_visualization_1769970092845.jpg'
    },
    {
        slug: 'metaweb-first-native-consumer',
        title: "The First Native Consumer: Why AI Agents Were Built for the MetaWeb",
        description: "AI agents are the MetaWeb's first and most prolific consumers. They don't experience friction — they experience protocol. The infrastructure exists today.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['MetaWeb', 'AI Agents', 'Micropayments', 'MCP', 'Tokens'],
        featured: true,
        image: '/ai_agent_native_consumer_1769969641745.jpg'
    },
    {
        slug: 'metaweb-in-hindsight-obvious',
        title: "In Hindsight, It Was Obvious",
        description: "Every component of the MetaWeb already existed. Micropayments, tokenisation, peer-to-peer serving, speculation, gated access. The assembly was always obvious.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '10 min read',
        tags: ['MetaWeb', 'Tokens', 'Micropayments', 'NFT', 'Bitcoin', 'History'],
        featured: true,
        image: '/hindsight_fragments_clarity_1769967220098.jpg'
    },
    {
        slug: 'metaweb-hype-crush',
        title: "The Hype Crush: How Crypto-Token Fever Bootstraps the MetaWeb",
        description: "New protocols don't die because they're technically inferior—they die because nobody shows up first. The MetaWeb has an irrational engine built into its core.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['MetaWeb', 'Tokens', 'Speculation', 'Adoption', 'Economics'],
        featured: true,
        image: '/hype_crush_tsunami_network_1769966534749.jpg'
    },
    {
        slug: 'metaweb-token-is-not-the-product',
        title: "MetaWeb: The Token Is the Product, the Token Is Not the Product",
        description: "A proposal for a different kind of internet where access, payment, and distribution are intrinsic to content. Understanding the deliberate paradox.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '10 min read',
        tags: ['MetaWeb', 'Tokens', 'Micropayments', 'Web3', 'Bitcoin'],
        featured: true,
        image: '/metaweb_interlocking_rings_assembly_1769967719495.jpg'
    },
    {
        slug: 'floop-the-browser-that-pays-you-to-think',
        title: "FLOOP! - Feedback Loop Webwallet & Browser",
        description: "An essay on the privacy-first browser where every click is an atomic swap, your reading history is yours alone, and the $FLOOP token aligns everyone's incentives.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['FLOOP', 'Browser', 'Tokens', 'BSV', 'Privacy', 'Web3'],
        featured: true,
        image: '/images/blog/floop-hero.jpg'
    },
    {
        slug: 'from-path-names-to-price-names',
        title: "From Path Names to Price Names: Economic Directories and the Tokenised Search Engine",
        description: "The $ sign is doing more work than anyone realises. How path resolution meets economic infrastructure to create the next generation of search.",
        date: '2026-02-01',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '15 min read',
        tags: ['Tokens', 'Search', 'BSV', 'Infrastructure', 'Web3'],
        featured: true,
        image: '/images/blog/from-path-names-to-price-names.jpg'
    },
    {
        slug: 'bruce-wayne-is-not-batman',
        title: "Bruce Wayne Is NOT Batman",
        description: "Court Enters Declarative Judgment; Judge Mellow Ends Gotham's Wildest Rumor. The BatComputer is an evidence machine.",
        date: '2026-02-01',
        author: { name: 'The Gotham Gazette', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Satire', 'Bitcoin', 'Evidence', 'Justice'],
        featured: true,
        image: '/images/blog/bruce-wayne-is-not-batman.jpg'
    },
    {
        slug: 'what-tokens-actually-are',
        title: "What Tokens Actually Are",
        description: "Tokens aren't a crypto thing. They're an ownership thing. Bearer assets that represent equity, tradeable without changing title on your cap table.",
        date: '2026-01-30',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Tokens', 'Equity', 'Startups', 'Bearer Instruments'],
        featured: true,
        image: '/images/blog/what-tokens-actually-are.jpg'
    },
    {
        slug: 'tokenize-your-app-for-1000',
        title: "Launch Your App in 24Hrs for $999",
        description: "A startup studio that charges $999/month and takes 1% equity. Stop anytime.",
        date: '2026-01-30',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Startup', 'Launch', 'Kintsugi', 'Founders', 'Equity'],
        featured: true,
        image: '/blog/one-percent-deal.png'
    },
    {
        slug: 'teamwork-makes-the-meme-work',
        title: "Teamwork Makes the Memework",
        description: "We're building a portfolio of tokenized apps. Builders get equity. Investors get access. This is the call.",
        date: '2026-01-30',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['Services', 'Tools', 'Blockchain', 'AI', 'Startup'],
        featured: true,
        image: '/blog/teamwork-memework.png'
    },
    {
        slug: 'anatomy-of-a-bitcoin-empire',
        title: "Anatomy of an Empire: An Inventory of the Bitcoin Corporation",
        description: "A deep dive into the 60+ distinct primitives, tools, and applications that make up the sprawling digital empire of the Bitcoin Corporation.",
        date: '2026-01-29',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '15 min read',
        tags: ['Bitcoin', 'Architecture', 'Engineering', 'Governance', 'Software'],
        featured: true,
        image: '/blog/anatomy-empire.png'
    },
    {
        slug: 'blueprint-of-the-bitcoin-corporation',
        title: 'Blueprint of The Bitcoin Corporation: Visualizing an On-Chain Organization',
        description: 'An exploration of how the Bitcoin Corporation is structured using the Cashboard, mapping executive roles to technical primitives and product suites.',
        date: '2026-01-29',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['Bitcoin', 'Governance', 'Cashboard', 'Engineering', 'Web3'],
        featured: true,
        image: '/blog/blueprint-of-the-bitcoin-corporation.png'
    },
    {
        slug: 'introduction-to-bitcoin-writer',
        title: 'Introduction to Bitcoin Writer',
        description: 'Bitcoin Writer is a word processor that saves your documents to the blockchain. Permanently. Immutably. Yours.',
        date: '2026-01-26',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['Bitcoin', 'Blockchain', 'Writing', 'Tokens', 'bWriter'],
        featured: true,
        image: '/images/clientprojects/bitcoin-writer/bitcoin-writer.png'
    },
    {
        slug: 'why-rwas-are-confusing',
        title: 'Why "RWAs" Are Confusing',
        description: '"Real World Assets" sounds precise, but trying to bucket gold and stocks into the same category collapses important distinctions. b0ase.com is tokenising digital reality, not just physical commodities.',
        date: '2026-01-25',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ['RWA', 'Tokenization', 'Digital Assets', 'Blockchain', 'Philosophy'],
        featured: true,
        image: '/images/blog/gold-vs-digital.png'
    },
    {
        slug: 'using-digital-gold-to-build-companies',
        title: "Using Digital Gold to Build Companies",
        description: "Gold and Bitcoin are stores of value that rely on patience. Building companies requires velocity, coordination, and the right bets. Kintsugi Contracts bridge the two.",
        date: '2026-01-25',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Bitcoin', 'Startups', 'Kintsugi', 'Venture Capital', 'Investment Strategy'],
        featured: true,
        image: '/images/blog/digital-kintsugi.jpg'
    },
    {
        slug: 'protocol-as-offer',
        title: "Protocol as Offer: The Legal Grammar of Kintsugi",
        description: "How Unilateral Contract Doctrine provides the legal primitives for Kintsugi's subscription-for-equity engine.",
        date: '2026-01-24',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ["Legal", "Kintsugi", "Bitcoin", "Smart Contracts", "Unilateral Contract"],
        featured: true,
        image: '/images/blog/protocol-as-offer-kintsugi.png'
    },
    {
        slug: 'shannon-autonomous-ai-pentester',
        title: "Shannon: The Autonomous AI Pentester",
        description: "Shannon is your fully autonomous AI pentester. It doesn't just scan for vulnerabilities; it executes real exploits to prove them, bridging the gap between fast AI coding and slow security audits.",
        date: '2026-01-25',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['AI', 'Security', 'Pentesting', 'Shannon', 'Keygraph', 'DevSecOps'],
        featured: true,
        image: '/images/blog/shannon-pentester.png'
    },
    {
        slug: 'claude-shannon-information-theory',
        title: "The Man Who Turned Meaning Into Math",
        description: "In 1948, a 32-year-old engineer wrote a paper that created the digital age. Claude Shannon didn't just describe information — he defined it. And once you understand his trick, you'll see it everywhere.",
        date: '2026-01-24',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['Information Theory', 'Claude Shannon', 'Mathematics', 'History', 'Technology'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1600&q=90'
    },
    {
        slug: 'tokens-as-auth-the-tradeable-cookie',
        title: "Tokens as Auth: The Tradeable Cookie",
        description: "What if your login credentials were assets? What if tracking cookies could be sold on secondary markets? Developer tokens that grant API access, tradeable on exchanges. The future of authentication is ownership.",
        date: '2026-01-23',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['Tokens', 'Authentication', 'Cookies', 'Developers', 'API', 'Trading'],
        featured: true,
        image: '/images/blog/tokens-auth.png'
    },
    {
        slug: 'moneybutton-path-to-10-million',
        title: "The MoneyButton Thesis: How a Penny-Press Economy Reaches $10M",
        description: "Every press costs less than a penny. Every press mints tokens. Every press spreads virally across the internet. Here's how MoneyButton.store is building the most addictive micropayment game on Bitcoin.",
        date: '2026-01-23',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['MoneyButton', 'Tokens', 'Micropayments', 'Bitcoin', 'Viral', 'Vibecoding'],
        featured: true,
        image: '/images/clientprojects/moneybutton-store/money-button-banner.png'
    },
    {
        slug: 'rise-of-the-hyper-founder',
        title: "Rise of the Hyper Founder",
        description: "Why the era of the singular startup is ending, and the age of the ecosystem-builder is beginning. Hyper Founders launch multiple projects, spawn ecosystems, and act as incubators of ideas rather than creators of a single product.",
        date: '2026-01-22',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ["Entrepreneurship", "Web3", "Hyper Founders", "Vibecoins", "Tokenization", "Ecosystem Building"],
        featured: true,
        image: '/images/blog/hyper-founder.png'
    },
    {
        slug: 'kintsugi-contracts',
        title: "Repairing the Future: Kintsugi Contracts",
        description: "Choose a b0ase.com app, pledge to build it or fund it, and earn your equity. The Kintsugi Engine is now open for repairs.",
        date: '2026-01-21',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ["Kintsugi", "Development", "Investment", "b0ase", "Equity", "AI"],
        featured: true,
        image: '/images/blog/kintsugi-2.png'
    },
    {
        slug: 'kintsugi-engine-transform-problems-into-products',
        title: "The Kintsugi Engine: Transform Your Broken Processes Into Golden Products",
        description: "Your startup in a box for £999. Describe your idea. Get tokens, a website, social media, and everything you need to raise capital. You keep 99%.",
        date: '2026-01-21',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Kintsugi', 'Startup', 'Fundraising', 'Tokens', 'b0ase', 'Software Development'],
        featured: true,
        image: '/images/blog/kintsugi-3.png'
    },
    {
        slug: 'bitcoin-spreadsheets-token-launch',
        title: "Bitcoin Spreadsheets: Crowdfunding the First bApp",
        description: "A real company. A clear roadmap. A compliant crowdfunding model. Bitcoin Spreadsheets is raising development funding through milestone-based token tranches.",
        date: '2026-01-20',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'The Bitcoin Corporation', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['Vibecoins', 'Bitcoin Spreadsheets', 'Tokenization', 'BSV', 'The Bitcoin Corporation', 'b0ase', 'Crowdfunding'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=90'
    },
    {
        slug: 'b0ase-is-a-vibecoin-factory',
        title: "b0ase.com Is a Vibecoin Factory",
        description: "We're not just writing about vibecoins. We're building the infrastructure to produce them. Here's how the factory works.",
        date: '2026-01-20',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Vibecoins', 'Tokenization', 'Vibe-Coding', 'b0ase', 'Product', 'Infrastructure'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1600&q=90'
    },
    {
        slug: 'why-vibecoins',
        title: "Why Vibecoins?",
        description: "Vibecoins start from low valuations while already having a product. Money raised goes directly to growth. Iteration happens at lightspeed. The risk/reward is gigantic compared to anything we've bet on before.",
        date: '2026-01-20',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ['Vibecoins', 'Tokenization', 'Crypto', 'Startups', 'Product'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=1600&q=90'
    },
    {
        slug: 'why-are-banks-still-gatekeeping-our-accounts',
        title: "Why Are Banks Still Gatekeeping Our Accounts?",
        description: "My bank locked me out for three months. With no access to my statements, I couldn't file my confirmation statement. Companies House threatened to prosecute me. Why is this still how the system works?",
        date: '2026-01-20',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Banking', 'Blockchain', 'Compliance', 'Infrastructure', 'Companies House'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1600&q=90'
    },
    {
        slug: 'what-saas-taught-me-about-blockchain',
        title: "What SaaS Taught Me About Blockchain",
        description: "For a long time, I thought I understood SaaS. I didn't. What I thought SaaS was, in hindsight, was closer to platform building, stack worship, or even infrastructure speculation.",
        date: '2026-01-20',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['SaaS', 'Blockchain', 'Startup', 'Business', 'Crypto', 'Strategy'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&q=90'
    },
    {
        slug: 'http-402-bitcoin-original-sin',
        title: 'HTTP 402: The Missing Link of the Web',
        description: 'Why the 402 Payment Required error code remained a ghost for decades, and how the original Bitcoin protocol was designed to fill that void before it was buried.',
        date: '2026-01-19',
        author: { name: 'Richard Boase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['Bitcoin', 'Web Standards', 'BSV', 'History', 'HTTP 402'],
        featured: true,
        image: '/images/blog/http-402-cover.jpg'
    },
    {
        slug: 'peer-revolution-equity-crowdfunding',
        title: 'The Peer Revolution: Equity Crowdfunding & The Rise of the Vibe-Coder',
        description: 'How b0ase.com is replacing VC with a peer-to-peer "Feature Funding" pipeline that turns code into capital. Investors fund features, developers get paid, and everyone gets equity.',
        date: '2026-01-19',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Equity Crowdfunding', 'Tokenization', 'Vibe-Coding', 'Web3', 'BSV'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1600&q=90'
    },
    {
        slug: 'ai-agents-shouldnt-sign-contracts',
        title: 'AI Agents Shouldn\'t Sign Contracts — Humans Should',
        description: 'There\'s a lot of noise about autonomous AI agents making deals. Most of it collapses under one fact: AI agents can\'t be held accountable. Here\'s how to do it right.',
        date: '2026-01-18',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['AI', 'Contracts', 'BSV', 'Agents', 'Legal'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1600&q=90'
    },
    {
        slug: 'applied-ai-problem-solver',
        title: 'The Human in the Loop: How Applied AI Solves Real Business Problems',
        description: 'Why your next software problem needs an AI-augmented freelancer, not another expensive consultant or overwhelmed team.',
        date: '2026-01-17',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['AI', 'Consulting', 'Software Development', 'Agentic Workflows', 'Problem Solving', 'Freelancing'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=90'
    },
    {
        slug: 'peer-tokens-how-it-works',
        title: 'Peer Tokens: How It Actually Works',
        description: 'You want to let people invest in you. Not in a company. In you - your work, your projects, whatever you build over time. Here\'s how to do it legally, transparently, and without spending thousands on lawyers.',
        date: '2026-01-17',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['Tokenisation', 'Peer Tokens', 'Investment', 'BSV', 'BOASE'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=90'
    },
    {
        slug: 'uk-tokenised-equity-j30s',
        title: 'Tokenised Equity in the UK: J30s, Share Certificates, and On-Chain Registers',
        description: 'While America argues about stablecoin yield, the UK has functional company law that already works with tokenisation. No new legislation needed. Just existing Companies Act structures, implemented on-chain.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Tokenisation', 'UK Company Law', 'J30', 'Share Certificates', 'Blockchain', 'Companies House', 'Equity'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=90'
    },
    {
        slug: 'clarity-act-banking-legislation',
        title: 'The CLARITY Act: When Banks Can\'t Compete, They Legislate',
        description: '53 banking associations just wrote themselves a $6.6 trillion protection bill. They called it the CLARITY Act. Meanwhile, Brian Armstrong discovers principles when they\'re convenient.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '9 min read',
        tags: ['Regulation', 'Stablecoins', 'Banking', 'CLARITY Act', 'Crypto', 'Coinbase', 'Regulatory Capture'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1600&q=90'
    },
    {
        slug: 'why-bitcoin-tokenised-shares-question',
        title: 'Why Use Bitcoin for Tokenised Shares? The Question Nobody Answers',
        description: 'If tokenised equity is the future, why isn\'t Companies House using it? A critical look at blockchain-based share registers and the uncomfortable questions the true believers avoid.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Bitcoin', 'Blockchain', 'Tokenisation', 'Companies House', 'Equity', 'Regulation'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=1600&q=90'
    },
    {
        slug: '100x-business-with-ai-agents',
        title: 'Building Production AI Agents: Lessons from Enterprise Deployments',
        description: 'Real lessons from deploying production AI agents at enterprise scale. What works, what doesn\'t, and how to build agents that actually deliver value in production environments.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '12 min read',
        tags: ['AI', 'Agents', 'Enterprise', 'Automation', 'Production', 'Business Strategy'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&q=90'
    },
    {
        slug: 'markdown-auto-discovery-experiment',
        title: 'The Third Audience: Making b0ase.com AI-Readable',
        description: 'We made every page on b0ase.com available as Markdown for AI agents. Here\'s what happened in the first 24 hours.',
        date: '2026-01-16',
        author: { name: 'b0ase.com', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['AI', 'SEO', 'GEO', 'Markdown', 'Content Strategy'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=1600&q=90'
    },
    {
        slug: 'why-vibecoding-needs-professional-maintenance',
        title: 'Why Vibecoding Needs Professional Maintenance',
        description: 'Vibecoding is incredible for building software fast. But who maintains it when things break? Why SaaS isn\'t dead, and how b0ase.com offers the best of both worlds: AI-powered development with professional maintenance.',
        date: '2026-01-16',
        author: { name: 'b0ase.com', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['AI', 'Development', 'SaaS', 'Maintenance', 'Business Strategy'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1600&q=90'
    },
    {
        slug: 'why-we-build-on-bsv',
        title: 'Why We Build on BSV',
        description: 'Every blockchain claims to be fast, cheap, and scalable. Most are lying. After building production systems on Ethereum, Solana, and Bitcoin SV, we\'ve learned what actually matters. Here\'s why we chose BSV—and why it\'s not even close.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['BSV', 'Bitcoin', 'Blockchain', 'Infrastructure', 'Scalability'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1600&q=90'
    },
    {
        slug: 'why-developers-deserve-equity',
        title: 'Why Developers Deserve Equity in What They Build',
        description: 'The most valuable code in the world is maintained by volunteers. The most used libraries are built in spare time. Something is fundamentally broken about how we compensate software developers. Here\'s why it\'s time for change.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '6 min read',
        tags: ['Open Source', 'Economics', 'Equity', 'Developer Rights', 'Web3'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1600&q=90'
    },
    {
        slug: 'turn-your-code-into-capital',
        title: 'Turn Your Code Into Capital: The Future of Repository Tokenization',
        description: 'You\'ve built something valuable. Your GitHub stars prove it. Now it\'s time to turn that open source work into investable assets. Here\'s how repository tokenization is changing the economics of software development.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Tokenization', 'Open Source', 'GitHub', 'BSV', 'Blockchain', 'Developers'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1600&q=90'
    },
    {
        slug: 'build-real-products-fast-with-b0ase',
        title: 'Build Real Products, Fast: The b0ase.com Stack',
        description: 'Most blockchain platforms give you tools and tell you to figure it out. We give you working components you can integrate in hours, not months. Here\'s what makes the b0ase.com stack different—and why developers choose us.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['Platform', 'Development', 'Infrastructure', 'APIs', 'Tokenization'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1600&q=90'
    },
    {
        slug: 'ai-powered-content-businesses',
        title: 'Building AI-Powered Content Businesses: A Professional Framework',
        description: 'From faceless YouTube channels to automated newsletters, AI is transforming content creation. But most creators are building on shaky foundations. Here\'s the professional framework for sustainable AI content businesses.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '7 min read',
        tags: ['AI', 'Content', 'Business', 'Automation', 'Strategy'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1600&q=90'
    },
    {
        slug: 'ai-money-2026-faceless-content-trend',
        title: 'How to Make $1M in 2026 with AI - The Faceless Content Trend',
        description: 'Faceless AI-generated content is dominating YouTube, TikTok, and Instagram. Here\'s the playbook everyone\'s using to build six-figure content businesses without showing their face.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '5 min read',
        tags: ['AI', 'Content Creation', 'Business', 'YouTube', 'Social Media'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1600&q=90'
    },
    {
        slug: '28-startup-lessons-learned-the-hard-way',
        title: '28 Startup Lessons I Wish Someone Had Told Me Before I Started',
        description: 'After working with hundreds of startups, these are the patterns that separate successful founders from the ones who burn through funding. Hard lessons that took years to learn.',
        date: '2026-01-16',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '10 min read',
        tags: ['Startups', 'Business', 'Entrepreneurship', 'Lessons Learned'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?w=1600&q=90'
    },
    {
        slug: 'why-bitcoin-authentication',
        title: 'Why Bitcoin Authentication Matters',
        description: 'Passwords are broken. OAuth is centralized. It\'s time for cryptographic authentication that puts users in control. Here\'s why Bitcoin auth is the future—and why b0ase.com is uniquely positioned to integrate it into your architecture.',
        date: '2026-01-14',
        author: { name: '@b0ase', url: 'https://twitter.com/b0ase' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '8 min read',
        tags: ['Bitcoin', 'Authentication', 'Web3', 'Security', 'Blockchain'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=1600&q=90'
    },
    {
        slug: 'bitcoin-auth-technical-guide',
        title: 'Bitcoin Authentication: Technical Integration Guide',
        description: 'A comprehensive technical guide to integrating Bitcoin-based authentication into your application. Learn the cryptographic foundations, implementation patterns, and security best practices for building production-ready Bitcoin auth systems.',
        date: '2026-01-15',
        author: { name: 'B0ASE Team', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '20 min read',
        tags: ['Bitcoin', 'Authentication', 'Security', 'Web3', 'Technical', 'BSV', 'Cryptography'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1555952494-efd681c7e3f9?w=1600&q=90'
    },
    {
        slug: 'quishing',
        title: 'The Square Trap: Why Security Teams Miss QR Phishing',
        description: 'North Korean state-backed hackers are turning QR codes into credential-stealing weapons to bypass enterprise security.',
        date: '2026-01-09',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        readTime: '4 min read',
        tags: ['Cyber Security', 'Phishing', 'North Korea'],
        image: '/images/blog/quishing-skull.png'
    },
    {
        slug: 'node-js-security-update-jan-2026',
        title: 'Tuesday, January 13, 2026 Security Releases',
        description: 'Critical Node.js security updates for 20.x, 22.x, 24.x and 25.x release lines addressing high-severity vulnerabilities including buffer allocation leaks and permissions bypasses.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-13',
        readTime: '5 min read',
        tags: ['Security', 'Node.js', 'Vulnerability'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1600&q=90'
    },
    // ARCHIVED: why-your-startup-looks-cheap (2026-01-22)
    // {
    //     slug: 'why-your-startup-looks-cheap',
    //     title: 'Why Your Startup Looks Cheap',
    //     description: '50 reasons your product fails the first-impression test. From generic AI logos to broken buttons, here is how to build a premium brand.',
    //     author: { name: 'b0ase', url: 'https://b0ase.com' },
    //     company: { name: 'b0ase.com', url: 'https://b0ase.com' },
    //     date: '2026-01-14',
    //     readTime: '5 min read',
    //     tags: ['Startup', 'Design', 'Business'],
    //     featured: true,
    //     image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=90'
    // },
    {
        slug: 'scale-your-business-with-ai-agents',
        title: 'Scale Your Business with AI Agents',
        description: 'How we build autonomous AI systems that let small teams compete with enterprises. Our production-tested approach to business automation.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-13',
        readTime: '6 min read',
        tags: ['AI Agents', 'Automation', 'Business'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600&q=90'
    },
    {
        slug: 'replace-your-marketing-team-with-ai',
        title: 'Replace Your Marketing Team with AI',
        description: 'Build complete marketing campaigns in minutes, not weeks. Market research, avatars, value ladders, and full sales pages - all automated.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-12',
        readTime: '8 min read',
        tags: ['AI Agents', 'Marketing', 'Content'],
        featured: true,
        image: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=1600&q=90'
    },
    {
        slug: 'ship-faster-with-ai-development',
        title: 'Ship Faster: AI-Powered Development',
        description: 'How we deliver production-ready code in days instead of months. The new operating system for building software.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-11',
        readTime: '5 min read',
        tags: ['Development', 'AI', 'Productivity'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1600&q=90'
    },
    {
        slug: 'automate-customer-support-24-7',
        title: 'Automate Customer Support 24/7',
        description: 'Deploy AI agents that handle support tickets, answer questions, and escalate issues - without hiring a team.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-10',
        readTime: '6 min read',
        tags: ['Customer Support', 'AI Agents', 'Automation'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=1600&q=90'
    },
    {
        slug: 'why-small-teams-beat-big-agencies',
        title: 'Why Small Teams Beat Big Agencies',
        description: 'The overhead that kills agency projects and how lean teams with AI tooling deliver better results faster.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-09',
        readTime: '5 min read',
        tags: ['Business', 'Agencies', 'Productivity'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1600&q=90'
    },
    {
        slug: 'the-real-cost-of-building-in-house',
        title: 'The Real Cost of Building In-House',
        description: 'Hiring developers vs buying components. A breakdown of the hidden costs most founders miss.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-08',
        readTime: '7 min read',
        tags: ['Business', 'Development', 'Costs'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1600&q=90'
    },
    {
        slug: 'from-idea-to-launch-in-two-weeks',
        title: 'From Idea to Launch in Two Weeks',
        description: 'A case study of building and launching a complete SaaS product in fourteen days using pre-built components.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-07',
        readTime: '8 min read',
        tags: ['Case Study', 'SaaS', 'Launch'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1600&q=90'
    },
    {
        slug: 'ai-agents-vs-chatbots',
        title: 'AI Agents vs Chatbots: What Actually Works',
        description: 'The difference between scripted chatbots and autonomous agents, and why it matters for your business.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-06',
        readTime: '6 min read',
        tags: ['AI Agents', 'Chatbots', 'Technology'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=1600&q=90'
    },
    {
        slug: 'building-for-blockchain-without-the-complexity',
        title: 'Building for Blockchain Without the Complexity',
        description: 'How we handle Web3 integration, token systems, and on-chain verification so you can focus on your product.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-05',
        readTime: '6 min read',
        tags: ['Blockchain', 'Web3', 'Development'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1600&q=90'
    },
    {
        slug: 'the-component-library-approach',
        title: 'The Component Library Approach',
        description: 'Why we build from proven components instead of starting from scratch, and how it benefits our clients.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-04',
        readTime: '5 min read',
        tags: ['Development', 'Components', 'Process'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=1600&q=90'
    },
    {
        slug: 'what-makes-a-good-technical-spec',
        title: 'What Makes a Good Technical Spec',
        description: 'The document that determines whether your project succeeds or fails. How to write specs that actually work.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-03',
        readTime: '6 min read',
        tags: ['Process', 'Documentation', 'Development'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1600&q=90'
    },
    {
        slug: 'starting-2026-with-a-new-approach',
        title: 'Starting 2026 with a New Approach',
        description: 'Our philosophy on building software in the age of AI. What changes, what stays the same.',
        author: { name: 'b0ase', url: 'https://b0ase.com' },
        company: { name: 'b0ase.com', url: 'https://b0ase.com' },
        date: '2026-01-01',
        readTime: '4 min read',
        tags: ['Company', 'AI', 'Philosophy'],
        featured: false,
        image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&q=90'
    }
];

export function getBlogPost(slug: string): BlogPost | undefined {
    return blogPosts.find(post => post.slug === slug);
}

export function getFeaturedPosts(): BlogPost[] {
    return blogPosts.filter(post => post.featured);
}

export function getPostsByTag(tag: string): BlogPost[] {
    return blogPosts.filter(post => post.tags.includes(tag));
}
