import { App } from "octokit";

// Initialize the GitHub App
// Credentials must be in .env.local
const appId = process.env.KINTSUGI_APP_ID;
const privateKey = process.env.KINTSUGI_PRIVATE_KEY?.replace(/\\n/g, '\n'); // Handle newlines in env
const installationId = process.env.KINTSUGI_INSTALLATION_ID;

export const getGitHubApp = () => {
    if (!appId || !privateKey) {
        throw new Error("Missing KINTSUGI_APP_ID or KINTSUGI_PRIVATE_KEY");
    }
    return new App({
        appId,
        privateKey,
    });
};

export const getInstallationOctokit = async () => {
    const app = getGitHubApp();
    if (!installationId) {
        throw new Error("Missing KINTSUGI_INSTALLATION_ID");
    }
    return await app.getInstallationOctokit(Number(installationId));
};

export const createPrivateRepo = async (repoName: string, description?: string) => {
    const octokit = await getInstallationOctokit();

    // Get Org name from installation? Or usage 'ai-kintsugi' hardcoded?
    // We can fetch the installation details to check the account login
    // But usually we create in the installation owner's account.

    try {
        // 1. Create Repo
        const { data: repo } = await octokit.rest.repos.createInOrg({
            org: 'ai-kintsugi', // Target Organization
            name: repoName,
            description: description || 'Generated by Kintsugi AI',
            private: true,
            auto_init: true, // Init with README
        });

        // 2. Add 'kintsugi-bot' (if needed) or verified user?
        // App automatically has access.

        return repo;
    } catch (error: any) {
        console.error("Error creating repo:", error);
        throw new Error(`GitHub Create Failed: ${error.message}`);
    }
};
