-- Seed Video data
INSERT INTO "Video" (filename, url, "projectSlug") VALUES
  ('NPGX.mp4', '/videos/NPGX.mp4', 'npg'),
  ('npg-red-slug.mp4', '/videos/npg-red-slug.mp4', 'npg'),
  ('A_train_rushes_past_while_urban_.mp4', '/videos/A_train_rushes_past_while_urban_.mp4', 'cherry'),
  ('zoom_around_the_party_picnic_and.mp4', '/videos/zoom_around_the_party_picnic_and.mp4', 'cherry'),
  ('fade_the_letters_so_see_the_sing.mp4', '/videos/fade_the_letters_so_see_the_sing.mp4', 'cherry'),
  ('zero-dice-slug-video-01.mp4', '/videos/zero-dice-slug-video-01.mp4', 'vexvoid'),
  ('zero-dice-02.mp4', '/videos/zero-dice-02.mp4', 'vexvoid'),
  ('zero-dice-03.mp4', '/videos/zero-dice-03.mp4', 'vexvoid'),
  ('zero-dice-04.mp4', '/videos/zero-dice-04.mp4', 'vexvoid'),
  ('Professional_Mode_Generated_Video (2).mp4', '/videos/Professional_Mode_Generated_Video (2).mp4', 'aivj'),
  ('Professional_Mode_zoom_and_flip_the_letters____go_ (1).mp4', '/videos/Professional_Mode_zoom_and_flip_the_letters____go_ (1).mp4', 'aivj'),
  ('Professional_Mode_zoom_and_flip_the_letters____go_ (2).mp4', '/videos/Professional_Mode_zoom_and_flip_the_letters____go_ (2).mp4', 'aivj'),
  ('Standard_Mode_Generated_Video.mp4', '/videos/Standard_Mode_Generated_Video.mp4', 'aivj'),
  ('Extended_Video.mp4', '/videos/Extended_Video.mp4', 'aivj');

-- Seed Audio data
INSERT INTO "Audio" (filename, url, "projectSlug") VALUES
  ('Cherry Graffiti.mp3', '/music/Cherry Graffiti.mp3', 'cherry'),
  ('Cherry Graffiti (1).mp3', '/music/Cherry Graffiti (1).mp3', 'cherry'),
  ('Cherry Graffiti (2).mp3', '/music/Cherry Graffiti (2).mp3', 'cherry'),
  ('Midnight Graffiti Symphony.mp3', '/music/Midnight Graffiti Symphony.mp3', 'cherry'),
  ('Midnight Murals.mp3', '/music/Midnight Murals.mp3', 'cherry'),
  ('Shadow Steps.mp3', '/music/Shadow Steps.mp3', 'cherry'),
  ('Digital Ghosts.mp3', '/music/Digital Ghosts.mp3', 'vexvoid'),
  ('Digital Ghosts (1).mp3', '/music/Digital Ghosts (1).mp3', 'vexvoid'),
  ('Digital Ghosts (2).mp3', '/music/Digital Ghosts (2).mp3', 'vexvoid'),
  ('Glitch in the Wind.mp3', '/music/Glitch in the Wind.mp3', 'vexvoid'),
  ('Glitch in the Wind (1).mp3', '/music/Glitch in the Wind (1).mp3', 'vexvoid'),
  ('Glitch in the Fog.mp3', '/music/Glitch in the Fog.mp3', 'vexvoid'),
  ('Shattered Frequencies.mp3', '/music/Shattered Frequencies.mp3', 'vexvoid'),
  ('Shattered Frequencies (1).mp3', '/music/Shattered Frequencies (1).mp3', 'vexvoid'),
  ('Shattered Signals.mp3', '/music/Shattered Signals.mp3', 'vexvoid'),
  ('Shattered Signals (1).mp3', '/music/Shattered Signals (1).mp3', 'vexvoid'),
  ('Static Dreams.mp3', '/music/Static Dreams.mp3', 'aivj'),
  ('Static Reverie.mp3', '/music/Static Reverie.mp3', 'aivj'),
  ('Fragments of Static.mp3', '/music/Fragments of Static.mp3', 'aivj'),
  ('Echo Chamber.mp3', '/music/Echo Chamber.mp3', 'aivj'),
  ('P_XEL _Øptik_ V.2.mp3', '/music/P_XEL _Øptik_ V.2.mp3', 'aivj'),
  ('ambient1.mp3', '/music/ambient1.mp3', 'npg'),
  ('ambient2.mp3', '/music/ambient2.mp3', 'npg'),
  ('ambient3.mp3', '/music/ambient3.mp3', 'npg'),
  ('ambient4.mp3', '/music/ambient4.mp3', 'npg'),
  ('ambient5.mp3', '/music/ambient5.mp3', 'npg');
