export const gigData = [
  {
    title: 'I will build a responsive website with audio and video content',
    description: 'Create stunning, professional WordPress websites and landing pages using Elementor Pro. I specialize in responsive design, custom functionality, and SEO optimization. From business websites to e-commerce stores, I deliver pixel-perfect designs that convert visitors into customers. Includes mobile optimization, speed optimization, and ongoing support.',
    category: 'Development',
    sub_category: 'WordPress Development',
    skills_required: 'WordPress, Elementor Pro, PHP, HTML/CSS, JavaScript, SEO, Responsive Design',
    budget_type: 'fixed' as const,
    budget_amount_min: '300',
    budget_amount_max: '1500',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'WordPress, Elementor Pro, responsive design, landing page, website development, SEO',
    deadline: '',
    is_published: true,
    fiverr_url: 'https://www.fiverr.com/richardboase/build-a-responsive-wordpress-website-or-landing-page-with-elementor-pro',
  },
  {
    title: 'I will build a custom admin dashboard for your application',
    description: 'Transform your business operations with a powerful, custom admin dashboard! I\'ll build a professional, user-friendly admin interface that streamlines your workflow and provides real-time insights.',
    category: 'Development',
    sub_category: 'Admin Dashboard',
    skills_required: 'React, Next.js, TypeScript, Tailwind CSS, Database Design',
    budget_type: 'hourly' as const,
    budget_amount_min: '80',
    budget_amount_max: '300',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'admin dashboard, react, nextjs, typescript, analytics',
    deadline: '',
    is_published: true,
    fiverr_url: 'https://www.fiverr.com/s/1qxm9m4',
  },
  {
    title: 'I will integrate Supabase backend services into your application',
    description: 'Seamlessly integrate Supabase for authentication, database management, storage, and real-time functionalities. I will ensure your application is scalable and secure with Supabase.',
    category: 'Development',
    sub_category: 'Backend Integration',
    skills_required: 'Supabase, PostgreSQL, Authentication, Real-time, Storage',
    budget_type: 'hourly' as const,
    budget_amount_min: '50',
    budget_amount_max: '100',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'Supabase, backend, database, authentication, real-time',
    deadline: '',
    is_published: true,
    fiverr_url: 'https://www.fiverr.com/richardboase/integrate-supabase-backend-services-into-your-application?context_referrer=seller_page&ref_ctx_id=a6bbd3a59abc4cd4b1d046ce3dc19a16&pckg_id=1&pos=3&seller_online=true&imp_id=6cb5b315-f9e1-48ad-826b-e9725c9c0c1f',
  },
  {
    title: 'I will create custom AI agents and autonomous workers for your business',
    description: 'Transform your business operations with custom AI agents and autonomous workers. I specialize in creating intelligent automation solutions that handle customer service, data processing, content generation, and workflow optimization. From chatbots to data analysis bots, I build AI solutions that work 24/7 to scale your business efficiently.',
    category: 'AI & Automation',
    sub_category: 'AI Agents',
    skills_required: 'OpenAI API, LangChain, Python, JavaScript, API Integration, AI/ML',
    budget_type: 'fixed' as const,
    budget_amount_min: '500',
    budget_amount_max: '3000',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'AI agents, automation, chatbots, OpenAI, LangChain, business automation',
    deadline: '',
    is_published: true,
    fiverr_url: 'https://www.fiverr.com/richardboase/create-custom-ai-agents-and-autonomous-workers-for-your-business?utm_medium=shared&utm_source=copy_link&utm_campaign=base_gig_create_share&utm_term=xXQvWBQ&view=gig&gig_id=441380382',
  }
]; 